#Загрузить базовый образ Ubuntu 18.04
FROM ubuntu:18.04

COPY jre-8u231-linux-x64.tar.gz /tmp/jre.tar.gz

RUN tar -xvzf /tmp/jre.tar.gz -C /opt && \
    update-alternatives --install /usr/bin/java java /opt/jre1.8.0_231/bin/java 2042 && \
    update-alternatives --install /usr/bin/keytool javac /opt/jre1.8.0_231/bin/keytool 2042 && \
    rm -rf /tmp/**

ENV JAVA_HOME /opt/jre1.8.0_231
ENV LC_ALL C.UTF-8
ENV TZ UTC-3